name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, develop ]

jobs:

  build-linux:
    name: Linux build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        sudo apt-get install libwebkit2gtk-4.0 gtk+-3.0
        go get -v -t -d ./...

    - name: Build
      run: go build -v ./...

    - name: Tests
      run: go test -v ./...

  build-macos:
    name: MacOS build
    runs-on: macos-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      run: go build -v ./...

    - name: Tests
      run: go test -v ./...

  build-windows:
    name: Windows Build
    runs-on: windows-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      run: go build -v ./...

    - name: Tests
      run: go test -v ./...
